---
title: "3.Progress_CPC-GENE_RNA"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(BoutrosLab.plotting.general)

#####READ TABLE#####


#CPC-GENE RNA-seq data - 2018-01-23_rnaseq_rsem_gene_FPKM
cpcg.fpkm <- read.delim(
   file = "~/Documents/1.Project/1.CPCGENE_RNA-seq/Rawdata/2018-01-23_rnaseq_rsem_gene_FPKM.txt", 
   row.names = 1
   );


```


```{r}

#Number of patient
patient.part <- c(1:(ncol(cpcg.fpkm)-1));
top.patient <- round(length(patient.part)*0.05, digit = 0);
low.patient <- round(length(patient.part)*0.95, digit = 0);



```


#Calculate using Median 
```{r, fig.width=11, fig.height=10}
#Calculate Median
cpcg.median <- function(x) {
   gene <- t(cpcg.fpkm[x,patient.part])
   gene.median <- median(gene)
   gene.median
   }
#patient.median <- data.frame();
#for (i in 1:nrow(cpcg.fpkm)){
#  patient.median[i,1] <- cpcg.median(i)
#};


#Calculate MAD
cpcg.mad <- function(x) {
   gene <- t(cpcg.fpkm[x,patient.part])
   gene.mad <- mad(gene)
   gene.mad
   }
#patient.mad <- data.frame();
#for (i in 1:nrow(cpcg.fpkm)){
#  patient.mad[i,1] <- cpcg.mad(i)
#};


#Make Z-score matrix - Using recalculated Median and MAD

zscore.gene.median <- function(x){
   (cpcg.fpkm[x,patient.part] - patient.median[x,]) / patient.mad[x,]
   }
#zscore.bymedian <- data.frame();
#for (i in 1 : nrow(cpcg.fpkm)) {
#  zscore.bymedian[i,1:length(patient.part)] <- zscore.gene.median(i)
#};
# zscore.bymedian.symbol <- cbind(zscore.bymedian, 
#                                 data.frame(cpcg.fpkm$Symbol), 
#                                 patient.median, 
#                                 patient.mad);
# colnames(zscore.bymedian.symbol) <- c(colnames(cpcg.fpkm), "Median", "mad");
# write.table(zscore.bymedian.symbol, 
#             file = 'cpcg.zscore.bymedian.txt', 
#             sep = "\t", 
#             col.names = TRUE, 
#             row.names = TRUE, 
#             quote = FALSE);
cpcg.zscore.bymedian <- read.delim(
   file = "~/Documents/1.Project/1.CPCGENE_RNA-seq/Rawdata/cpcg.zscore.bymedian.txt", 
   row.names = 1
   );

#Gene order - have high z-score range: max(z-score)-min(z-score) - all genes : Using Median and MAD
z.max.median <- apply(cpcg.zscore.bymedian[patient.part], 1, max);
z.min.median <- apply(cpcg.zscore.bymedian[patient.part], 1, min);
z.range.median <- z.max.median - z.min.median;
z.range.median <- data.frame(z.range.median);
cpcg.zscore.zrange.median <- cbind(cpcg.zscore.bymedian, z.range.median);
cpcg.zrange.decrease.median <- cpcg.zscore.zrange.median[order(cpcg.zscore.zrange.median$z.range.median, decreasing = TRUE),];
#write.table(cpcg.zrange.decrease.median, file = '~/Documents/1.Project/1.CPCGENE_RNA-seq/Rawdata/cpcg.zrange.decrease.median.txt', sep = "\t", col.names = TRUE, row.names = TRUE, quote = FALSE)

```

#Calculate using Median - Make Heatmap
```{r, fig.width=11, fig.height=10}

#Heatmap - for 200 genes
zscore.heat <- create.heatmap(
   x = cpcg.zrange.decrease.median[1:200,patient.part],
   clustering.method = "complete",
   yaxis.lab = NA,
   yaxis.cex = 0.3,
   xaxis.lab = cpcg.zrange.decrease.median$Symbol,
   xaxis.cex = 0.5,
   main = "Z-score by Median - Top 200 genes",
   main.cex = 1.5,
   grid.col = FALSE,
   print.colour.key = TRUE,
   yaxis.tck = 0.1,
   xaxis.tck = 0.1,
   colour.scheme = c('red4', 'white', 'dodgerblue4'),
   colour.centering.value = 0,
   at = seq(-5,5,0.001),
   colourkey.cex = 1,
   resolution = 300,
   rows.distance.method = 'euclidean',
   cols.distance.method = 'manhattan'
   );
zscore.heat;

```

#Calculate using Median - Make Waterfall plot
```{r, fig.width=9, fig.height=6}

#Make multiplot for z-score and FPKM value (Median)
for (i in 1:100) {
   a <- t(cpcg.zrange.decrease.median[i,patient.part])
   z.gene <- as.numeric(cpcg.zrange.decrease.median[i,patient.part])
   row.a <- data.frame(row.names(a))
   gene.a <- cbind(row.a, z.gene)
   colnames(gene.a) <- c("patient", "gene")
   fraction.bar <- create.barplot(
      formula = gene ~ patient,
      data = gene.a,
      main = cpcg.zrange.decrease.median$Symbol[i],
      main.cex = 1.5,
      ylab.lab = 'Z-Score',
      yaxis.cex = 1,
      ylab.cex = 1,
      xaxis.tck = 0.2,
      xlab.lab = "Patient",
      xaxis.rot = 90,
      xaxis.cex = 0.5,
      xlab.cex = 1,
      yaxis.tck = 1,
      yaxis.fontface = 'bold',
      sample.order = 'decreasing'
      )
  
   fpkm.gene <- as.numeric(cpcg.fpkm[rownames(cpcg.zrange.decrease.median)[i],patient.part])
   fpkm.b <- cbind(row.a, fpkm.gene)
   colnames(fpkm.b) <- c("patient", "gene")
   nonzero.fpkm <- round(sum(ifelse(fpkm.b$gene == 0, 0, 1))/length(patient.part)*100, 2)
   fpkm.bar <- create.barplot(
      formula = gene ~ patient,
      data = fpkm.b,
      main = cpcg.zrange.decrease.median$Symbol[i],
      main.cex = 1.5,
      ylab.lab = 'FPKM',
      yaxis.cex = 1,
      ylab.cex = 1,
      xaxis.tck = 0.2,
      xlab.lab = "Patient",
      xaxis.rot = 90,
      xaxis.cex = 0.5,
      xlab.cex = 1,
      yaxis.tck = 1,
      yaxis.fontface = 'bold',
      sample.order = 'decreasing'
      )
 
   final.plot <- create.multiplot(
      plot.objects = list(fpkm.bar, fraction.bar),
      main = cpcg.zrange.decrease.median$Symbol[i],
      xlab.label = "Patient",
      ylab.label = c("Z-score", "FPKM"),
      y.relation = "free",
      main.cex = 1.5,
      xaxis.cex = 0.6,
      yaxis.cex = 0.7,
      ylab.cex = 1,
      xlab.cex = 1,
      xaxis.rot = 90,
      xaxis.tck = 0.2,
      key = list(
        title = expression(underline("Fraction of patient")),
           text = list(
              lab = paste(as.character(nonzero.fpkm),"%"),
              cex = 1.1,
              col = 'black'
              ),
        x = 0.75,
        y = 0.4,
        padding.text = 3,
        columns = 1
        ),
      resolution = 50
      )
  print(final.plot)
};

```



#Calculate using Mean
```{r}

#Calculate mean - without the 5% highest and 5% lowest values
cpcg.trimmean <- function(x) {
   gene <- t(cpcg.fpkm[x,patient.part])
   gene.mean <- mean(gene, trim = 0.05)
   gene.mean
   }

#patient.trimmean <- data.frame();
#for (i in 1:nrow(cpcg.fpkm)){
#  patient.trimmean[i,1] <- cpcg.trimmean(i)
#};


#Calculate SD - without the 5% highest and 5% lowest values
cpcg.tramsd <- function(x) {
   gene <- t(cpcg.fpkm[x,patient.part])
   gene.order <- gene[order(gene, decreasing = TRUE),]
   gene.order.sd <- gene.order.SD <- sd(gene.order[(top.patient+1):(low.patient)])
   gene.order.sd
   }
patient.trimsd <- data.frame();
for (i in 1:nrow(cpcg.fpkm)){
  patient.trimsd[i,1] <- cpcg.tramsd(i)
};


#Make Z-score matrix - Using recalculated mean and SD : without the 5% highest and 5% lowest values
zscore.gene.trimmean <- function(x){
   (cpcg.fpkm[x,patient.part] - patient.trimmean[x,]) / patient.trimsd[x,]
   }
#zscore.bytrimmean <- data.frame();
#for (i in 1 : nrow(cpcg.fpkm)) {
#  zscore.bytrimmean[i,1:length(patient.part)] <- zscore.gene.trimmean(i)
#};
# zscore.bytrimmean.symbol <- cbind(zscore.bytrimmean, 
#                                   data.frame(cpcg.fpkm$Symbol), 
#                                   patient.trimmean, 
#                                   patient.trimsd);
# colnames(zscore.bytrimmean.symbol) <- c(colnames(cpcg.fpkm), "Trimmean", "Trimsd");
# write.table(zscore.bytrimmean.symbol, 
#             file = 'cpcg.zscore.bytrimmean.txt', 
#             sep = "\t", 
#             col.names = TRUE, 
#             row.names = FALSE, 
#             quote = FALSE)
cpcg.zscore.bytrimmean <- read.delim(
   file = "~/Documents/1.Project/1.CPCGENE_RNA-seq/Rawdata/cpcg.zscore.bytrimmean.txt", 
   row.names = 1
   );


#Gene order - have high z-score range: max(z-score)-min(z-score) - all genes
z.max.trimmean <- apply(cpcg.zscore.bytrimmean[patient.part], 1, max);
z.min.trimmean <- apply(cpcg.zscore.bytrimmean[patient.part], 1, min);
z.range.trimmean <- z.max.trimmean - z.min.trimmean;
z.range.trimmean <- data.frame(z.range.trimmean);
cpcg.zscore.zrange.trimmean <- cbind(cpcg.zscore.bytrimmean, z.range.trimmean);
cpcg.zrange.decrease.trimmean <- cpcg.zscore.zrange.trimmean[order(cpcg.zscore.zrange.trimmean$z.range.trimmean, decreasing = TRUE),];
# write.table(cpcg.zrange.decrease.trimmean, 
#             file = '~/Documents/1.Project/1.CPCGENE_RNA-seq/Rawdata/cpcg.zrange.decrease.trimmean.txt', 
#             sep = "\t", 
#             col.names = TRUE, 
#             row.names = TRUE, 
#             quote = FALSE);


```

#Calculate using Mean - Make Heatmap
```{r, fig.width=11, fig.height=10}
#Heatmap - for 100 genes
zscore.heat <- create.heatmap(
   x = cpcg.zrange.decrease.trimmean[1:200,patient.part],
   clustering.method = "complete",
   #clustering.method = "none",
   main = "Z-score by Mean - Top 200 genes",
   main.cex = 1.5,
   yaxis.lab = NA,
   yaxis.cex = 0.3,
   xaxis.lab = cpcg.zrange.decrease.trimmean$Symbol,
   xaxis.cex = 0.5,
   # show each colour once (i.e, four values, four colours)
   grid.col = FALSE,
   print.colour.key = TRUE,
   # remove y-axis ticks
   yaxis.tck = 0.1,
   xaxis.tck = 0.1,
   #height = 1,
   colour.scheme = c('red4', 'white', 'dodgerblue4'),
   colour.centering.value = 0,
   #colourkey.labels.at = seq(-5,5,1),
   at = seq(-5,5,0.001),
   colourkey.cex = 1,
   #force.grid.col = TRUE,
   #row.colour = "black"
   resolution = 300,
   rows.distance.method = 'euclidean',
   cols.distance.method = 'manhattan'
   );
zscore.heat;
```


#Calculate using Mean - Make Waterfall plot
```{r, fig.width=9, fig.height=6}


#Make multiplot for z-score and FPKM value (Mean)
for (i in 1:100) {
   a <- t(cpcg.zrange.decrease.trimmean[i,patient.part])
   z.gene <- as.numeric(cpcg.zrange.decrease.trimmean[i,patient.part])
   row.a <- data.frame(row.names(a))
   gene.a <- cbind(row.a, z.gene)
   colnames(gene.a) <- c("patient", "gene")
   fraction.bar <- create.barplot(
      formula = gene ~ patient,
      data = gene.a,
      main = cpcg.zrange.decrease.trimmean$Symbol[i],
      main.cex = 1.5,
      ylab.lab = 'Z-Score',
      #ylimits = c(0,1),
      #yat = seq(0,1,0.5),
      yaxis.cex = 1,
      ylab.cex = 1,
      xaxis.tck = 0.2,
      #xaxis.lab = NA,
      xlab.lab = "Patient",
      xaxis.rot = 90,
      xaxis.cex = 0.5,
      xlab.cex = 1,
      yaxis.tck = 1,
      yaxis.fontface = 'bold',
      #ylab.axis.padding	= 3,
      sample.order = 'decreasing'
      )
  
   fpkm.gene <- as.numeric(cpcg.fpkm[rownames(cpcg.zrange.decrease.trimmean)[i],patient.part])
   fpkm.b <- cbind(row.a, fpkm.gene)
   colnames(fpkm.b) <- c("patient", "gene")
   nonzero.fpkm <- round(sum(ifelse(fpkm.b$gene == 0, 0, 1))/length(patient.part)*100, 2)
   fpkm.bar <- create.barplot(
      formula = gene ~ patient,
      data = fpkm.b,
      main = cpcg.zrange.decrease.trimmean$Symbol[i],
      main.cex = 1.5,
      ylab.lab = 'FPKM',
      #ylimits = c(0,1),
      #yat = seq(0,1,0.5),
      yaxis.cex = 1,
      ylab.cex = 1,
      xaxis.tck = 0.2,
      #xaxis.lab = NA,
      xlab.lab = "Patient",
      xaxis.rot = 90,
      xaxis.cex = 0.5,
      xlab.cex = 1,
      yaxis.tck = 1,
      yaxis.fontface = 'bold',
      #ylab.axis.padding	= 3,
      sample.order = 'decreasing'
      )

   final.plot <- create.multiplot(
      plot.objects = list(fpkm.bar, fraction.bar),
      main = cpcg.zrange.decrease.trimmean$Symbol[i],
      xlab.label = "Patient",
      # The plotting function throws an error if this is not included
      ylab.label = c("Z-score", "FPKM"),
      #ylab.padding = 7,
      # Parameters set in the multiplot will override settings in individual plots
      y.relation = "free",
      main.cex = 1.5,
      xaxis.cex = 0.6,
      yaxis.cex = 0.7,
      ylab.cex = 1,
      xlab.cex = 1,
      xaxis.rot = 90,
      xaxis.tck = 0.2,
      key = list(
         title = expression(underline("Fraction of patient")),
            text = list(
               lab = paste(as.character(nonzero.fpkm),"%"),
               cex = 1.1,
               col = 'black'
               ),
         x = 0.75,
         y = 0.4,
         padding.text = 3,
         columns = 1
         ),
      resolution = 50
      )
   print(final.plot)
};



 
```


#Compare gene list between Median-derived and Mean-derived data
```{r, fig.width=6, fig.height=4}

##Median
#Check the z-score range distribution
hist(cpcg.zrange.decrease.median$z.range.median,
     breaks = 500,
     main = "Z-score Range Distribution (Median)",
     xlab = "Z-score Range"
     )
#Cutoff of outlier - z-score range 100
hist(cpcg.zrange.decrease.median$z.range.median,
     breaks = 2000,
     main = "Z-score Range Distribution (Median); cutoff",
     xlab = "Z-score Range",
     xlim = c(0,500),
     ylim = c(0,100) #limit for frequency 
     )
median.cutoff <- cpcg.zrange.decrease.median[cpcg.zrange.decrease.median$z.range.median > 100,]
median.cutoff <- na.omit(median.cutoff)


##Mean
#Check the z-score range distribution
hist(cpcg.zrange.decrease.trimmean$z.range.trimmean,
     breaks = 500,
     main = "Z-score Range Distribution (Mean)",
     xlab = "Z-score Range"
     )
#Cutoff of outlier - z-score range 100
hist(cpcg.zrange.decrease.trimmean$z.range.trimmean,
     breaks = 2000,
     main = "Z-score Range Distribution (Mean); cutoff",
     xlab = "Z-score Range",
     xlim = c(0,500),
     ylim = c(0,100) #limit for frequency 
     )
mean.cutoff <- cpcg.zrange.decrease.trimmean[cpcg.zrange.decrease.trimmean$z.range.trimmean > 100,]
mean.cutoff <- na.omit(mean.cutoff)


```
